### ISSUE TITLE
Memory leaks in parser for incorrect yara rules (rules_fuzzer, LeakSanitizer)

### ISSUE THREAD

**Issue by forzafedor** [VirusTotal/yara#2114]
**Describe the bug**
When I fuzzed the targets of the 'rules_fuzzer' target on my hardware, a crash with a memory leak was detected
[crash-report.txt](https://github.com/user-attachments/files/17463049/crash-report.txt)

**To Reproduce**
```bash
export CXX="clang++"
export CC="clang"
export LDFLAGS="-fsanitize=address,undefined"
export CFLAGS="-fsanitize=fuzzer-no-link,address,undefined -g"
export CXXFLAGS="-fsanitize=fuzzer-no-link,address,undefined -g"
git clone --depth 1 https://github.com/VirusTotal/yara.git
cd yara
./bootstrap.sh
./configure --enable-macho --enable-debug --enable-dex --enable-dotnet --without-crypto
make clean 
make -j$(nproc) all
make install

$CXX $CXXFLAGS "-fsanitize=fuzzer" -std=c++11 ./tests/oss-fuzz/rules_fuzzer.cc -o ../rules_fuzzer ./.libs/libyara.a
wget https://github.com/user-attachments/files/17463049/crash-report.txt -O crash-report.txt 

./rules_fuzzer crash-report.txt
```
**Log**
```C
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1563862527
INFO: Loaded 1 modules   (80264 inline 8-bit counters): 80264 [0x56474f771628, 0x56474f784fb0),
INFO: Loaded 1 PC tables (80264 PCs): 80264 [0x56474f784fb0,0x56474f8be830),
/mnt/c/project/yara/rules_fuzzer: Running 1 inputs 1 time(s) each.
Running: crash-report.txt

=================================================================
==62785==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0x56474ef105ca in strdup (/mnt/c/project/yara/rules_fuzzer+0x4665ca) (BuildId: 12b569c5a48b7e315e7afc4b3a870f45f56cef9d)
    #1 0x56474efdb6fb in yr_strdup /mnt/c/project/yara/libyara/mem.c:142:10
    #2 0x56474ef93d43 in yara_yylex /mnt/c/project/yara/libyara/lexer.l:492:22
    #3 0x56474f2ee032 in yara_yyparse /mnt/c/project/yara/libyara/grammar.c:2052:16
    #4 0x56474efd5f40 in yr_lex_parse_rules_string /mnt/c/project/yara/libyara/lexer.l:947:3
    #5 0x56474ef768f9 in yr_compiler_add_string /mnt/c/project/yara/libyara/compiler.c:679:10
    #6 0x56474ef682a7 in LLVMFuzzerTestOneInput /mnt/c/project/yara/tests/oss-fuzz/rules_fuzzer.cc:62:7
    #7 0x56474ee75970 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/mnt/c/project/yara/cov_targets/rules_fuzzer+0x3cb970) (BuildId: 12b569c5a48b7e315e7afc4b3a870f45f56cef9d)
    #8 0x56474ee5fbd2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/mnt/c/project/yara/cov_targets/rules_fuzzer+0x3b5bd2) (BuildId: 12b569c5a48b7e315e7afc4b3a870f45f56cef9d)
    #9 0x56474ee654ba in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/mnt/c/project/yara/cov_targets/rules_fuzzer+0x3bb4ba) (BuildId: 12b569c5a48b7e315e7afc4b3a870f45f56cef9d)
    #10 0x56474ee8e682 in main (/mnt/c/project/yara/cov_targets/rules_fuzzer+0x3e4682) (BuildId: 12b569c5a48b7e315e7afc4b3a870f45f56cef9d)
    #11 0x7fb7e88b4d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: 9 byte(s) leaked in 1 allocation(s).

INFO: a leak has been found in the initial corpus.

INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
```

**Expected behavior**
All allocated memory will be freed.

**Please complete the following information:**
 - OS: Ubuntu 22.04.3 LTS
 - YARA version:  Master branch https://github.com/VirusTotal/yara/commit/548ba3d9c860e7b6c7286cbcf1f7e429cffe99f4

**Additional context**
The problem occurs when `YYMAXDEPTH` overflows and the FOR operator in the rule.

If the stack is not full, it clear up in `yyerrlab1` and the process of clearing the memory allocated for using the FOR operator occurs correctly (written below this place in log)
```
...
Error: popping token '(' ()
Stack now 0 1 8 14 18 19 21 24 27 30 35 41 50 71 96 147 210 230 247
Error: popping nterm $@7 ()
Stack now 0 1 8 14 18 19 21 24 27 30 35 41 50 71 96 147 210 230
Error: popping token ':' ()
Stack now 0 1 8 14 18 19 21 24 27 30 35 41 50 71 96 147 210
Error: popping nterm for_iteration ()
Stack now 0 1 8 14 18 19 21 24 27 30 35 41 50 71 96 147
Error: popping nterm $@6 ()
Stack now 0 1 8 14 18 19 21 24 27 30 35 41 50 71 96
Shifting token error ()
Entering state 146
Stack now 0 1 8 14 18 19 21 24 27 30 35 41 50 71 96 146
Reducing stack by rule 88 (line 1501):
   $1 = token "<for>" ()
   $2 = nterm for_expression ()
   $3 = token error ()
Stack now 0 1 8 14 18 19 21 24 27 30 35 41 50
Error: popping token ':' ()
Stack now 0 1 8 14 18 19 21 24 27 30 35 41
Error: popping token "<condition>" ()
Stack now 0 1 8 14 18 19 21 24 27 30 35
...
```

But if the stack is full, it clear up in `yyreturnlab` and the process of cleaning up the memory allocated for using the FOR operator is missing (written below this place in log)

```
...
Cleanup: popping token '(' ()
Cleanup: popping nterm $@7 ()
Cleanup: popping token ':' ()
Cleanup: popping nterm for_iteration ()
Cleanup: popping nterm $@6 ()
Cleanup: popping nterm for_expression ()
Cleanup: popping token "<for>" ()
Cleanup: popping token ':' ()
Cleanup: popping token "<condition>" ()
...
```

Thus, the memory allocated for the `1leak_var` (9 byte) (in the crash-report.txt example) was not free.

**Comment by plusvic** [comment]
Unfortunately that's a well-known issue in bison.
https://lists.gnu.org/archive/html/bug-bison/2005-04/msg00107.html

The leak is in the parsing code automatically generated by bison. Bison has a mechanism for destructing objects created by parser actions when the parsing fails, but that doesn't apply to symbols that are in the parser's stack when YYMAXDEPTH is reached.
