### ISSUE TITLE
Rule crashes yara

### ISSUE THREAD

**Issue by ZetaTwo** [VirusTotal/yara#490]
The following rule crashes yara

Ran like this:
```
$ yara rule1.yara . 
[1]    10304 segmentation fault (core dumped)  yara rule1.yara .
```

Version:
```
yara2 yara --version
yara 3.4.0
```

Backtrace:
```
#0  0x000000000042955b in ?? ()
#1  0x000000000042948e in ?? ()
#2  0x000000000042a03a in ?? ()
#3  0x0000000000426b92 in ?? ()
#4  0x0000000000426f94 in ?? ()
#5  0x000000000041e4b2 in ?? ()
#6  0x0000000000407fa1 in ?? ()
#7  0x0000000000402e6b in ?? ()
#8  0x00007ffff6c80830 in __libc_start_main (main=0x402ba0, argc=0x3, 
    argv=0x7fffffffe458, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe448)
    at ../csu/libc-start.c:291
#9  0x0000000000403069 in ?? ()
```

Rule:
```
rule yara_challenge
{
	strings:
		$yara_challenge = { 51 8B 54 24 08 57 8B FA 83 C9 FF 33 C0 F2 AE 8B 44 24 14 F7 D1 49 48 3B C1 7D 05 33 C0 5F 59 C3 BF ?? ?? ?0 ?0 83 C9 FF 33 C0 55 F2 AE F7 D1 49 BF ?? ?? ?? ?? 8B E9 83 C9 FF F2 AE F7 D1 49 8B FA 89 4C 24 18 83 C9 FF F2 AE F7 D1 56 49 33 F6 89 4C 24 0C 85 C9 7E 6? 8B 4C 24 18 8B C2 2B C1 53 89 44 24 18 EB 04 8B 44 24 18 8B 4C 24 1C 8D 1C 0E 0F BE 14 18 52 68 ?? ?? ?0 ?0 ( E8 ?? 00 00 00 | FF ?? ?0 ?0 00 ?0 ) 8B F8 8B C6 99 F7 7C 24 28 81 EF ?? ?? ?0 ?0 0F BE 82 ?? ?? ?0 ?0 50 68 ?? ?? ?? ?? ( E8 ?? ?? ?? ?? | FF ?? ?0 ?0 00 ?0 ) 8D 8C 2F ?? ?? ?0 ?0 83 C4 10 2B C8 8B C1 99 F7 FD 8B 44 24 10 46 3B F0 8A 92 ?? ?? ?0 ?0 88 13 7C A? 5B 8B 44 24 18 C6 04 06 00 8B C6 5E 5D 5F 59 C3 }
	condition:
		 all of them 
}
```

**Comment by plusvic** [comment]
It's the same bug reported in #324. It's already fixed in the latest version.
