### ISSUE TITLE
Yara crashes on big-endian architectures

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#493]
Builds of Yara 3.5.0-2 on Debian's build servers fail their tests (segfault), see https://buildd.debian.org/status/package.php?p=yara

**Comment by hillu** [comment]
This is not a regression: Yara 3.4.0 also crashes on Debian unstable/powerpc architecture when checking a trivial rule `rule test { condition: true }`.

**Comment by hillu** [comment]
It looks like something is seriously wrong with encoding/decoding pointers for byteode and with storing pointers on the stack.

`test-rules`:
<pre>
Program received signal SIGSEGV, Segmentation fault.
yr_execute_code (rules=rules@entry=0x1013ea78, 
    context=context@entry=0xfffee7a8, timeout=timeout@entry=0, 
    start_time=start_time@entry=1470348868) at exec.c:448
448               rule->t_flags[tidx] |= RULE_TFLAGS_MATCH;
(gdb) bt
#0  yr_execute_code (rules=rules@entry=0x1013ea78, 
    context=context@entry=0xfffee7a8, timeout=timeout@entry=0, 
    start_time=start_time@entry=1470348868) at exec.c:448
#1  0x10015c48 in yr_rules_scan_mem_blocks (rules=rules@entry=0x1013ea78, 
    iterator=iterator@entry=0xfffef3d0, flags=flags@entry=0, 
    callback=callback@entry=0x10008aa0 <count_matches>, 
    user_data=user_data@entry=0xfffef408, timeout=timeout@entry=0)
    at rules.c:470
#2  0x10015f30 in yr_rules_scan_mem (rules=rules@entry=0x1013ea78, 
    buffer=buffer@entry=0x10045d08 "dummy", buffer_size=buffer_size@entry=5, 
    flags=flags@entry=0, callback=callback@entry=0x10008aa0 <count_matches>, 
    user_data=user_data@entry=0xfffef408, timeout=timeout@entry=0)
    at rules.c:582
#3  0x10008d2c in matches_blob (
    rule=0x10042ec4 "rule test { condition: true }", blob=<optimized out>, 
    len=<optimized out>) at tests/util.c:119
#4  0x10001a9c in test_boolean_operators () at tests/test-rules.c:37
#5  main (argc=<optimized out>, argv=<optimized out>)
    at tests/test-rules.c:1350
</pre>

`test-pe`:
<pre>
Program received signal SIGSEGV, Segmentation fault.
0x0fac2c18 in strlen () from /lib/powerpc-linux-gnu/libc.so.6
(gdb) bt
#0  0x0fac2c18 in strlen () from /lib/powerpc-linux-gnu/libc.so.6
#1  0x10003fa8 in yr_hash_table_lookup (table=0x10126e30, key=key@entry=0x0, 
    ns=ns@entry=0x0) at hash.c:275
#2  0x10006cd8 in yr_modules_load (module_name=module_name@entry=0x0, 
    context=context@entry=0xfffee7f8) at modules.c:127
#3  0x1002de28 in yr_execute_code (rules=rules@entry=0x10139928, 
    context=context@entry=0xfffee7f8, timeout=timeout@entry=0, 
    start_time=start_time@entry=1470348906) at exec.c:850
#4  0x1000ef48 in yr_rules_scan_mem_blocks (rules=rules@entry=0x10139928, 
    iterator=iterator@entry=0xfffef420, flags=flags@entry=0, 
    callback=callback@entry=0x10001da0 <count_matches>, 
    user_data=user_data@entry=0xfffef458, timeout=timeout@entry=0)
    at rules.c:470
#5  0x1000f230 in yr_rules_scan_mem (rules=rules@entry=0x10139928, 
    buffer=buffer@entry=0x100703e8 "MZ\220", 
    buffer_size=buffer_size@entry=32768, flags=flags@entry=0, 
    callback=callback@entry=0x10001da0 <count_matches>, 
    user_data=user_data@entry=0xfffef458, timeout=timeout@entry=0)
    at rules.c:582
#6  0x1000202c in matches_blob (
    rule=rule@entry=0x10039b18 "import \"pe\" rule test { condition: pe.imports(\"KERNEL32.dll\", \"DeleteCriticalSection\") }", blob=<optimized out>, 
    len=<optimized out>) at tests/util.c:119
#7  0x10001ab8 in main (argc=<optimized out>, argv=<optimized out>)
    at tests/test-pe.c:8
</pre>
