### ISSUE TITLE
Null pointer dereference in _yr_re_fiber_sync()

### ISSUE THREAD

**Issue by fumfel** [VirusTotal/yara#682]
**Null pointer dereference in _yr_re_fiber_sync()**

Git HEAD: 1b1198b2040426ebe5a60718511ca5313f93b3dd

[Payload](https://github.com/VirusTotal/yara/files/1071765/yara__yr_re_fiber_sync_null_ptr_deref.txt)

To reproduce:` yara yara__yr_re_fiber_sync_null_ptr_deref strings`

ASAN:

```
==27756==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000003c (pc 0x000000523ac8 bp 0x7ffcc0216190 sp 0x7ffcc0215fc0 T0)
==27756==The signal is caused by a READ memory access.
==27756==Hint: address points to the zero page.
    #0 0x523ac7 in _yr_re_fiber_sync XYZ/yara/libyara/re.c:1632:22
    #1 0x51aacd in yr_re_exec XYZ/yara/libyara/re.c:2166:11
    #2 0x53df67 in _yr_scan_verify_re_match XYZ/yara/libyara/scan.c:573:5
    #3 0x53f4f9 in yr_scan_verify_match XYZ/yara/libyara/scan.c:750:5
    #4 0x535ded in _yr_rules_scan_mem_block XYZ/yara/libyara/rules.c:276:9
    #5 0x537604 in yr_rules_scan_mem_blocks XYZ/yara/libyara/rules.c:452:5
    #6 0x5389f8 in yr_rules_scan_mem XYZ/yara/libyara/rules.c:586:10
    #7 0x5389f8 in yr_rules_scan_file XYZ/yara/libyara/rules.c:610
    #8 0x4ee799 in main XYZ/yara/yara.c:1228:14
    #9 0x7ff71797c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x41a458 in _start (XYZ/yara/yara+0x41a458)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV XYZ/yara/libyara/re.c:1632:22 in _yr_re_fiber_sync
==27756==ABORTING
```

**Comment by plusvic** [comment]
Fixed in 41af10045ccc9ffa57954adadcbafed991de28c6
