### ISSUE TITLE
Use of uninitialized value in re_yylex()

### ISSUE THREAD

**Issue by fumfel** [VirusTotal/yara#684]
**Use of uninitialized value in re_yylex()**

Git HEAD: 1818e5a326f3c22a71ba59a524a8d99b359a6c24

[Payload](https://github.com/VirusTotal/yara/files/1097028/yara_uouv_re_yylex.txt)

Command: `yara yara_uouv_re_yylex.yar /usr/bin/strings`

MSAN:

```
==19144==WARNING: MemorySanitizer: use-of-uninitialized-value
  #0 0x4ed83e in re_yylex XYZ/yara/libyara/re_lexer.l:332:7
  #1 0x5c0637 in re_yyparse XYZ/yara/libyara/re_grammar.c:1263:16
  #2 0x4f7483 in yr_parse_re_string XYZ/yara/libyara/re_lexer.l:616:3
  #3 0x5b8428 in yr_parser_reduce_string_declaration XYZ/yara/libyara/parser.c:529:31
  #4 0x56634b in yara_yyparse XYZ/yara/libyara/grammar.y:529:26
  #5 0x4bf49b in yr_lex_parse_rules_file XYZ/yara/libyara/lexer.l:822:3
  #6 0x49bae4 in yr_compiler_add_file XYZ/yara/libyara/compiler.c:357:12
  #7 0x4977ea in main XYZ/yara/yara.c:1137:17
  #8 0x7f02bc27682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
  #9 0x41b608 in _start (/usr/local/bin/yara+0x41b608)

SUMMARY: MemorySanitizer: use-of-uninitialized-value XYZ/yara/libyara/re_lexer.l:332:7 in re_yylex
```

**Comment by plusvic** [comment]
@fumfel I think this issue should be solved with the latest commit. I'm not able to verify it because MemorySanitizer doesn't seem to work with Mac OS X and I don't have a Linux machine around. Could you check if it works fine now?

**Comment by fumfel** [comment]
@plusvic In a484e862bf404cb785806db8449e87aa39028c11 problem solved :+1:
