### ISSUE TITLE
yara hangs on process scan

### ISSUE THREAD

**Issue by n0way0ut** [VirusTotal/yara#801]
running yara bin with

`for p in $(find rules/Malicious_Documents -type f -name "*.yar"); do sudo yara $p 23896 ; done
`
using the rules in 
https://github.com/Yara-Rules/rules

gives this output and the yara hangs and never finish.

```
rules/Malicious_Documents/Maldoc_MIME_ActiveMime_b64.yar(18): warning: $activemime is slowing down scanning
Contains_VBE_File 23896
rules/Malicious_Documents/Maldoc_PDF.yar(63): warning: $attrib contains .*, consider using .{N} with a reasonable value for N
rules/Malicious_Documents/Maldoc_PDF.yar(158): warning: $shell is slowing down scanning
rules/Malicious_Documents/Maldoc_PDF.yar(259): warning: $reg is slowing down scanning
rules/Malicious_Documents/Maldoc_PDF.yar(295): warning: $reg0 contains .*, consider using .{N} with a reasonable value for N
rules/Malicious_Documents/Maldoc_PDF.yar(296): warning: $reg1 contains .*, consider using .{N} with a reasonable value for N
rules/Malicious_Documents/Maldoc_PDF.yar(402): warning: $reg0 contains .*, consider using .{N} with a reasonable value for N
rules/Malicious_Documents/Maldoc_PDF.yar(403): warning: $reg1 contains .*, consider using .{N} with a reasonable value for N
```

$ yara --version
3.7.0

same behavior with python-yara

it works properly with a single yara rule file.

**Comment by plusvic** [comment]
Which operating system are you using? Is it Windows?

**Comment by n0way0ut** [comment]
yes, windows 10. It works good on file names, but it stucks on processes and the python CPU usage is always around 25%

**Comment by n0way0ut** [comment]
```
import yara
import sys

rule = yara.compile(filepath=sys.argv[1])
m = rule.match(pid=int(sys.argv[2]))
print(m)
```

```
rule ExampleRule
{
    strings:
        $my_text_string = "AAAAAA"

    condition:
        $my_text_string 
}

```

```
C:\Users\User\Desktop>python y.py test.yar 7560
Traceback (most recent call last):
  File "y.py", line 6, in <module>
    m = rule.match(pid=int(sys.argv[2]))
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\yara\rules.py", line 354, in match
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\yara\rules.py", line 326, in match_proc
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\yara\rules.py", line 179, in match
    fnc(*args)
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\yara\libyara_wrapper.py", line 570, in yr_scan_proc
yara.libyara_wrapper.YaraMatchError: Not enough memory

C:\Users\User\Desktop>pip show yara-python
Name: yara-python
Version: 3.7.0
Summary: Python interface for YARA
Home-page: https://github.com/VirusTotal/yara-python
Author: Victor M. Alvarez
Author-email: plusvic@gmail.com;vmalvarez@virustotal.com
License: Apache 2.0
Location: c:\users\user\appdata\local\programs\python\python36\lib\site-packages
Requires:

C:\Users\User\Desktop>python --version
Python 3.6.3
```

**Comment by n0way0ut** [comment]
it is yara-python related, opened there.
