### ISSUE TITLE
yara import error

### ISSUE THREAD

**Issue by cuckoo-linux** [VirusTotal/yara#934]
habo@habo-VirtualBox:~/HaboMalHunter$ python AnalyzeControl.py -v -l ./test/bin/read.64.elf
Traceback (most recent call last):
  File "AnalyzeControl.py", line 57, in <module>
    import static
  File "/home/habo/HaboMalHunter/static/__init__.py", line 14, in <module>
    from static_analyzer import *
  File "/home/habo/HaboMalHunter/static/static_analyzer.py", line 27, in <module>
    import yara
ImportError: No module named yara

**Comment by plusvic** [comment]
This looks like yara-python is not installed. Please try: `pip install yara-python`

**Comment by Envincion** [comment]
i did ,still getting same respond ,any idea ? i been trying to run Loki since 2 days now ,cant find a way
